### ISSUE TITLE
Installed using the Readme, getting errors on first start.

### ISSUE THREAD

**Issue by filviu** [mehdilauters/wifiScanMap#12]
Hi,

I installed using the steps in the readme on a pi2 with a usb gps. I get the following errors when starting:

````
root@raspberrypi:~/wifiScanMap# ./scanmap.py -m
WARNING: No route found for IPv6 destination :: (no default route?)
/root/wifiScanMap/src/GpsPoller.py:25: RuntimeWarning: This channel is already in use, continuing anyway.  Use GPIO.setwarnings(False) to disable warnings.
  GPIO.setup(self.gpio, GPIO.OUT, initial=GPIO.LOW)
Traceback (most recent call last):
  File "./scanmap.py", line 971, in <module>
    main(parse_args())
  File "./scanmap.py", line 959, in main
    app = Application(args)
  File "./scanmap.py", line 136, in __init__
    for esp in self.args.esp.split(','):
AttributeError: 'NoneType' object has no attribute 'split'
````

Any ideas what I'm doing wrong? Thanks!

**Comment by filviu** [comment]
Thank you :) Seems to be working now...
